//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DRP.Message.XWWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://www.139130.net")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMOMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMOMessageForNeedConfirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBusinessTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostSingleOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostMassOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportForNeedConfirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmMOMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetMediasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::DRP.Message.Properties.Settings.Default.DRP_Message_XWWebReference_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMOMessageCompletedEventHandler GetMOMessageCompleted;
        
        /// <remarks/>
        public event GetMOMessageForNeedConfirmCompletedEventHandler GetMOMessageForNeedConfirmCompleted;
        
        /// <remarks/>
        public event GetBusinessTypeCompletedEventHandler GetBusinessTypeCompleted;
        
        /// <remarks/>
        public event GetAccountInfoCompletedEventHandler GetAccountInfoCompleted;
        
        /// <remarks/>
        public event ModifyPasswordCompletedEventHandler ModifyPasswordCompleted;
        
        /// <remarks/>
        public event PostCompletedEventHandler PostCompleted;
        
        /// <remarks/>
        public event PostSingleCompletedEventHandler PostSingleCompleted;
        
        /// <remarks/>
        public event PostMassCompletedEventHandler PostMassCompleted;
        
        /// <remarks/>
        public event PostGroupCompletedEventHandler PostGroupCompleted;
        
        /// <remarks/>
        public event GetResponseCompletedEventHandler GetResponseCompleted;
        
        /// <remarks/>
        public event GetReportCompletedEventHandler GetReportCompleted;
        
        /// <remarks/>
        public event GetReportForNeedConfirmCompletedEventHandler GetReportForNeedConfirmCompleted;
        
        /// <remarks/>
        public event ConfirmReportCompletedEventHandler ConfirmReportCompleted;
        
        /// <remarks/>
        public event ConfirmMOMessageCompletedEventHandler ConfirmMOMessageCompleted;
        
        /// <remarks/>
        public event FindResponseCompletedEventHandler FindResponseCompleted;
        
        /// <remarks/>
        public event FindReportCompletedEventHandler FindReportCompleted;
        
        /// <remarks/>
        public event SetMediasCompletedEventHandler SetMediasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetMOMessage", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MOMsg[] GetMOMessage(string account, string password, int pagesize) {
            object[] results = this.Invoke("GetMOMessage", new object[] {
                        account,
                        password,
                        pagesize});
            return ((MOMsg[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMOMessageAsync(string account, string password, int pagesize) {
            this.GetMOMessageAsync(account, password, pagesize, null);
        }
        
        /// <remarks/>
        public void GetMOMessageAsync(string account, string password, int pagesize, object userState) {
            if ((this.GetMOMessageOperationCompleted == null)) {
                this.GetMOMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMOMessageOperationCompleted);
            }
            this.InvokeAsync("GetMOMessage", new object[] {
                        account,
                        password,
                        pagesize}, this.GetMOMessageOperationCompleted, userState);
        }
        
        private void OnGetMOMessageOperationCompleted(object arg) {
            if ((this.GetMOMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMOMessageCompleted(this, new GetMOMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetMOMessageForNeedConfirm", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MOMsg[] GetMOMessageForNeedConfirm(string account, string password, int pagesize, bool isNeedConfirm) {
            object[] results = this.Invoke("GetMOMessageForNeedConfirm", new object[] {
                        account,
                        password,
                        pagesize,
                        isNeedConfirm});
            return ((MOMsg[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMOMessageForNeedConfirmAsync(string account, string password, int pagesize, bool isNeedConfirm) {
            this.GetMOMessageForNeedConfirmAsync(account, password, pagesize, isNeedConfirm, null);
        }
        
        /// <remarks/>
        public void GetMOMessageForNeedConfirmAsync(string account, string password, int pagesize, bool isNeedConfirm, object userState) {
            if ((this.GetMOMessageForNeedConfirmOperationCompleted == null)) {
                this.GetMOMessageForNeedConfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMOMessageForNeedConfirmOperationCompleted);
            }
            this.InvokeAsync("GetMOMessageForNeedConfirm", new object[] {
                        account,
                        password,
                        pagesize,
                        isNeedConfirm}, this.GetMOMessageForNeedConfirmOperationCompleted, userState);
        }
        
        private void OnGetMOMessageForNeedConfirmOperationCompleted(object arg) {
            if ((this.GetMOMessageForNeedConfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMOMessageForNeedConfirmCompleted(this, new GetMOMessageForNeedConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetBusinessType", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BusinessType[] GetBusinessType(string account, string password) {
            object[] results = this.Invoke("GetBusinessType", new object[] {
                        account,
                        password});
            return ((BusinessType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBusinessTypeAsync(string account, string password) {
            this.GetBusinessTypeAsync(account, password, null);
        }
        
        /// <remarks/>
        public void GetBusinessTypeAsync(string account, string password, object userState) {
            if ((this.GetBusinessTypeOperationCompleted == null)) {
                this.GetBusinessTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusinessTypeOperationCompleted);
            }
            this.InvokeAsync("GetBusinessType", new object[] {
                        account,
                        password}, this.GetBusinessTypeOperationCompleted, userState);
        }
        
        private void OnGetBusinessTypeOperationCompleted(object arg) {
            if ((this.GetBusinessTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusinessTypeCompleted(this, new GetBusinessTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetAccountInfo", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountInfo GetAccountInfo(string account, string password) {
            object[] results = this.Invoke("GetAccountInfo", new object[] {
                        account,
                        password});
            return ((AccountInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string account, string password) {
            this.GetAccountInfoAsync(account, password, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(string account, string password, object userState) {
            if ((this.GetAccountInfoOperationCompleted == null)) {
                this.GetAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfo", new object[] {
                        account,
                        password}, this.GetAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoOperationCompleted(object arg) {
            if ((this.GetAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoCompleted(this, new GetAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/ModifyPassword", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModifyPassword(string account, string old_password, string new_password) {
            object[] results = this.Invoke("ModifyPassword", new object[] {
                        account,
                        old_password,
                        new_password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyPasswordAsync(string account, string old_password, string new_password) {
            this.ModifyPasswordAsync(account, old_password, new_password, null);
        }
        
        /// <remarks/>
        public void ModifyPasswordAsync(string account, string old_password, string new_password, object userState) {
            if ((this.ModifyPasswordOperationCompleted == null)) {
                this.ModifyPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyPasswordOperationCompleted);
            }
            this.InvokeAsync("ModifyPassword", new object[] {
                        account,
                        old_password,
                        new_password}, this.ModifyPasswordOperationCompleted, userState);
        }
        
        private void OnModifyPasswordOperationCompleted(object arg) {
            if ((this.ModifyPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyPasswordCompleted(this, new ModifyPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/Post", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GsmsResponse Post(string account, string password, MTPacks mtpack) {
            object[] results = this.Invoke("Post", new object[] {
                        account,
                        password,
                        mtpack});
            return ((GsmsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PostAsync(string account, string password, MTPacks mtpack) {
            this.PostAsync(account, password, mtpack, null);
        }
        
        /// <remarks/>
        public void PostAsync(string account, string password, MTPacks mtpack, object userState) {
            if ((this.PostOperationCompleted == null)) {
                this.PostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOperationCompleted);
            }
            this.InvokeAsync("Post", new object[] {
                        account,
                        password,
                        mtpack}, this.PostOperationCompleted, userState);
        }
        
        private void OnPostOperationCompleted(object arg) {
            if ((this.PostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCompleted(this, new PostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/PostSingle", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PostSingle(string account, string password, string mobile, string content, string subid) {
            object[] results = this.Invoke("PostSingle", new object[] {
                        account,
                        password,
                        mobile,
                        content,
                        subid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PostSingleAsync(string account, string password, string mobile, string content, string subid) {
            this.PostSingleAsync(account, password, mobile, content, subid, null);
        }
        
        /// <remarks/>
        public void PostSingleAsync(string account, string password, string mobile, string content, string subid, object userState) {
            if ((this.PostSingleOperationCompleted == null)) {
                this.PostSingleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostSingleOperationCompleted);
            }
            this.InvokeAsync("PostSingle", new object[] {
                        account,
                        password,
                        mobile,
                        content,
                        subid}, this.PostSingleOperationCompleted, userState);
        }
        
        private void OnPostSingleOperationCompleted(object arg) {
            if ((this.PostSingleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostSingleCompleted(this, new PostSingleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/PostMass", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PostMass(string account, string password, string[] mobiles, string content, string subid) {
            object[] results = this.Invoke("PostMass", new object[] {
                        account,
                        password,
                        mobiles,
                        content,
                        subid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PostMassAsync(string account, string password, string[] mobiles, string content, string subid) {
            this.PostMassAsync(account, password, mobiles, content, subid, null);
        }
        
        /// <remarks/>
        public void PostMassAsync(string account, string password, string[] mobiles, string content, string subid, object userState) {
            if ((this.PostMassOperationCompleted == null)) {
                this.PostMassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostMassOperationCompleted);
            }
            this.InvokeAsync("PostMass", new object[] {
                        account,
                        password,
                        mobiles,
                        content,
                        subid}, this.PostMassOperationCompleted, userState);
        }
        
        private void OnPostMassOperationCompleted(object arg) {
            if ((this.PostMassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostMassCompleted(this, new PostMassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/PostGroup", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PostGroup(string account, string password, MessageData[] mssages, string subid) {
            object[] results = this.Invoke("PostGroup", new object[] {
                        account,
                        password,
                        mssages,
                        subid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PostGroupAsync(string account, string password, MessageData[] mssages, string subid) {
            this.PostGroupAsync(account, password, mssages, subid, null);
        }
        
        /// <remarks/>
        public void PostGroupAsync(string account, string password, MessageData[] mssages, string subid, object userState) {
            if ((this.PostGroupOperationCompleted == null)) {
                this.PostGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostGroupOperationCompleted);
            }
            this.InvokeAsync("PostGroup", new object[] {
                        account,
                        password,
                        mssages,
                        subid}, this.PostGroupOperationCompleted, userState);
        }
        
        private void OnPostGroupOperationCompleted(object arg) {
            if ((this.PostGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostGroupCompleted(this, new PostGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetResponse", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MTResponse[] GetResponse(string account, string password, int PageSize) {
            object[] results = this.Invoke("GetResponse", new object[] {
                        account,
                        password,
                        PageSize});
            return ((MTResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetResponseAsync(string account, string password, int PageSize) {
            this.GetResponseAsync(account, password, PageSize, null);
        }
        
        /// <remarks/>
        public void GetResponseAsync(string account, string password, int PageSize, object userState) {
            if ((this.GetResponseOperationCompleted == null)) {
                this.GetResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResponseOperationCompleted);
            }
            this.InvokeAsync("GetResponse", new object[] {
                        account,
                        password,
                        PageSize}, this.GetResponseOperationCompleted, userState);
        }
        
        private void OnGetResponseOperationCompleted(object arg) {
            if ((this.GetResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResponseCompleted(this, new GetResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetReport", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MTReport[] GetReport(string account, string password, int PageSize) {
            object[] results = this.Invoke("GetReport", new object[] {
                        account,
                        password,
                        PageSize});
            return ((MTReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportAsync(string account, string password, int PageSize) {
            this.GetReportAsync(account, password, PageSize, null);
        }
        
        /// <remarks/>
        public void GetReportAsync(string account, string password, int PageSize, object userState) {
            if ((this.GetReportOperationCompleted == null)) {
                this.GetReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportOperationCompleted);
            }
            this.InvokeAsync("GetReport", new object[] {
                        account,
                        password,
                        PageSize}, this.GetReportOperationCompleted, userState);
        }
        
        private void OnGetReportOperationCompleted(object arg) {
            if ((this.GetReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportCompleted(this, new GetReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/GetReportForNeedConfirm", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MTReport[] GetReportForNeedConfirm(string account, string password, int PageSize, bool isNeedConfirm) {
            object[] results = this.Invoke("GetReportForNeedConfirm", new object[] {
                        account,
                        password,
                        PageSize,
                        isNeedConfirm});
            return ((MTReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportForNeedConfirmAsync(string account, string password, int PageSize, bool isNeedConfirm) {
            this.GetReportForNeedConfirmAsync(account, password, PageSize, isNeedConfirm, null);
        }
        
        /// <remarks/>
        public void GetReportForNeedConfirmAsync(string account, string password, int PageSize, bool isNeedConfirm, object userState) {
            if ((this.GetReportForNeedConfirmOperationCompleted == null)) {
                this.GetReportForNeedConfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportForNeedConfirmOperationCompleted);
            }
            this.InvokeAsync("GetReportForNeedConfirm", new object[] {
                        account,
                        password,
                        PageSize,
                        isNeedConfirm}, this.GetReportForNeedConfirmOperationCompleted, userState);
        }
        
        private void OnGetReportForNeedConfirmOperationCompleted(object arg) {
            if ((this.GetReportForNeedConfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportForNeedConfirmCompleted(this, new GetReportForNeedConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/ConfirmReport", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmReport(string account, string password, string confirmId) {
            object[] results = this.Invoke("ConfirmReport", new object[] {
                        account,
                        password,
                        confirmId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmReportAsync(string account, string password, string confirmId) {
            this.ConfirmReportAsync(account, password, confirmId, null);
        }
        
        /// <remarks/>
        public void ConfirmReportAsync(string account, string password, string confirmId, object userState) {
            if ((this.ConfirmReportOperationCompleted == null)) {
                this.ConfirmReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmReportOperationCompleted);
            }
            this.InvokeAsync("ConfirmReport", new object[] {
                        account,
                        password,
                        confirmId}, this.ConfirmReportOperationCompleted, userState);
        }
        
        private void OnConfirmReportOperationCompleted(object arg) {
            if ((this.ConfirmReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmReportCompleted(this, new ConfirmReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/ConfirmMOMessage", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ConfirmMOMessage(string account, string password, string confirmId) {
            object[] results = this.Invoke("ConfirmMOMessage", new object[] {
                        account,
                        password,
                        confirmId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmMOMessageAsync(string account, string password, string confirmId) {
            this.ConfirmMOMessageAsync(account, password, confirmId, null);
        }
        
        /// <remarks/>
        public void ConfirmMOMessageAsync(string account, string password, string confirmId, object userState) {
            if ((this.ConfirmMOMessageOperationCompleted == null)) {
                this.ConfirmMOMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmMOMessageOperationCompleted);
            }
            this.InvokeAsync("ConfirmMOMessage", new object[] {
                        account,
                        password,
                        confirmId}, this.ConfirmMOMessageOperationCompleted, userState);
        }
        
        private void OnConfirmMOMessageOperationCompleted(object arg) {
            if ((this.ConfirmMOMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmMOMessageCompleted(this, new ConfirmMOMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/FindResponse", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MTResponse[] FindResponse(string account, string password, string batchid, string mobile, int pageindex, int flag) {
            object[] results = this.Invoke("FindResponse", new object[] {
                        account,
                        password,
                        batchid,
                        mobile,
                        pageindex,
                        flag});
            return ((MTResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void FindResponseAsync(string account, string password, string batchid, string mobile, int pageindex, int flag) {
            this.FindResponseAsync(account, password, batchid, mobile, pageindex, flag, null);
        }
        
        /// <remarks/>
        public void FindResponseAsync(string account, string password, string batchid, string mobile, int pageindex, int flag, object userState) {
            if ((this.FindResponseOperationCompleted == null)) {
                this.FindResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindResponseOperationCompleted);
            }
            this.InvokeAsync("FindResponse", new object[] {
                        account,
                        password,
                        batchid,
                        mobile,
                        pageindex,
                        flag}, this.FindResponseOperationCompleted, userState);
        }
        
        private void OnFindResponseOperationCompleted(object arg) {
            if ((this.FindResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindResponseCompleted(this, new FindResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/FindReport", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MTReport[] FindReport(string account, string password, string batchid, string mobile, int pageindex, int flag) {
            object[] results = this.Invoke("FindReport", new object[] {
                        account,
                        password,
                        batchid,
                        mobile,
                        pageindex,
                        flag});
            return ((MTReport[])(results[0]));
        }
        
        /// <remarks/>
        public void FindReportAsync(string account, string password, string batchid, string mobile, int pageindex, int flag) {
            this.FindReportAsync(account, password, batchid, mobile, pageindex, flag, null);
        }
        
        /// <remarks/>
        public void FindReportAsync(string account, string password, string batchid, string mobile, int pageindex, int flag, object userState) {
            if ((this.FindReportOperationCompleted == null)) {
                this.FindReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindReportOperationCompleted);
            }
            this.InvokeAsync("FindReport", new object[] {
                        account,
                        password,
                        batchid,
                        mobile,
                        pageindex,
                        flag}, this.FindReportOperationCompleted, userState);
        }
        
        private void OnFindReportOperationCompleted(object arg) {
            if ((this.FindReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindReportCompleted(this, new FindReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.139130.net/SetMedias", RequestNamespace="http://www.139130.net", ResponseNamespace="http://www.139130.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MediaItems[] SetMedias(string fullPath) {
            object[] results = this.Invoke("SetMedias", new object[] {
                        fullPath});
            return ((MediaItems[])(results[0]));
        }
        
        /// <remarks/>
        public void SetMediasAsync(string fullPath) {
            this.SetMediasAsync(fullPath, null);
        }
        
        /// <remarks/>
        public void SetMediasAsync(string fullPath, object userState) {
            if ((this.SetMediasOperationCompleted == null)) {
                this.SetMediasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetMediasOperationCompleted);
            }
            this.InvokeAsync("SetMedias", new object[] {
                        fullPath}, this.SetMediasOperationCompleted, userState);
        }
        
        private void OnSetMediasOperationCompleted(object arg) {
            if ((this.SetMediasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetMediasCompleted(this, new SetMediasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MOMsg {
        
        private string phoneField;
        
        private string contentField;
        
        private int msgTypeField;
        
        private string specNumberField;
        
        private string serviceTypeField;
        
        private System.Nullable<System.DateTime> receiveTimeField;
        
        private string reserveField;
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int MsgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SpecNumber {
            get {
                return this.specNumberField;
            }
            set {
                this.specNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReceiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                this.receiveTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MTReport {
        
        private long idField;
        
        private string batchIDField;
        
        private string phoneField;
        
        private string msgIDField;
        
        private string customMsgIDField;
        
        private int stateField;
        
        private System.Nullable<int> totalField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<System.DateTime> submitTimeField;
        
        private System.Nullable<System.DateTime> doneTimeField;
        
        private string originResultField;
        
        private string reserveField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string batchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string msgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        public string customMsgID {
            get {
                return this.customMsgIDField;
            }
            set {
                this.customMsgIDField = value;
            }
        }
        
        /// <remarks/>
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> submitTime {
            get {
                return this.submitTimeField;
            }
            set {
                this.submitTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> doneTime {
            get {
                return this.doneTimeField;
            }
            set {
                this.doneTimeField = value;
            }
        }
        
        /// <remarks/>
        public string originResult {
            get {
                return this.originResultField;
            }
            set {
                this.originResultField = value;
            }
        }
        
        /// <remarks/>
        public string reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MTResponse {
        
        private string batchIDField;
        
        private string msgIDField;
        
        private string customMsgIDField;
        
        private int stateField;
        
        private string phoneField;
        
        private System.Nullable<int> totalField;
        
        private System.Nullable<int> numberField;
        
        private System.Nullable<System.DateTime> submitRespTimeField;
        
        private string originResultField;
        
        private string reserveField;
        
        private long idField;
        
        /// <remarks/>
        public string batchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string msgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        public string customMsgID {
            get {
                return this.customMsgIDField;
            }
            set {
                this.customMsgIDField = value;
            }
        }
        
        /// <remarks/>
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> submitRespTime {
            get {
                return this.submitRespTimeField;
            }
            set {
                this.submitRespTimeField = value;
            }
        }
        
        /// <remarks/>
        public string originResult {
            get {
                return this.originResultField;
            }
            set {
                this.originResultField = value;
            }
        }
        
        /// <remarks/>
        public string reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class GsmsResponse {
        
        private int resultField;
        
        private System.Guid uuidField;
        
        private string messageField;
        
        private string attributesField;
        
        /// <remarks/>
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MessageData {
        
        private string phoneField;
        
        private string contentField;
        
        private bool vipFlagField;
        
        private string customMsgIDField;
        
        private string customNumField;
        
        private MediaItems[] mediasField;
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public bool vipFlag {
            get {
                return this.vipFlagField;
            }
            set {
                this.vipFlagField = value;
            }
        }
        
        /// <remarks/>
        public string customMsgID {
            get {
                return this.customMsgIDField;
            }
            set {
                this.customMsgIDField = value;
            }
        }
        
        /// <remarks/>
        public string customNum {
            get {
                return this.customNumField;
            }
            set {
                this.customNumField = value;
            }
        }
        
        /// <remarks/>
        public MediaItems[] medias {
            get {
                return this.mediasField;
            }
            set {
                this.mediasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MediaItems {
        
        private string metaField;
        
        private byte[] dataField;
        
        /// <remarks/>
        public string meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class MTPacks {
        
        private string templateNumField;
        
        private System.Guid uuidField;
        
        private System.Guid batchIDField;
        
        private string batchNameField;
        
        private int sendTypeField;
        
        private int msgTypeField;
        
        private MediaItems[] mediasField;
        
        private MessageData[] msgsField;
        
        private int bizTypeField;
        
        private bool distinctFlagField;
        
        private long scheduleTimeField;
        
        private string remarkField;
        
        private string customNumField;
        
        private long deadlineField;
        
        /// <remarks/>
        public string templateNum {
            get {
                return this.templateNumField;
            }
            set {
                this.templateNumField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid batchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string batchName {
            get {
                return this.batchNameField;
            }
            set {
                this.batchNameField = value;
            }
        }
        
        /// <remarks/>
        public int sendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        public int msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        public MediaItems[] medias {
            get {
                return this.mediasField;
            }
            set {
                this.mediasField = value;
            }
        }
        
        /// <remarks/>
        public MessageData[] msgs {
            get {
                return this.msgsField;
            }
            set {
                this.msgsField = value;
            }
        }
        
        /// <remarks/>
        public int bizType {
            get {
                return this.bizTypeField;
            }
            set {
                this.bizTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool distinctFlag {
            get {
                return this.distinctFlagField;
            }
            set {
                this.distinctFlagField = value;
            }
        }
        
        /// <remarks/>
        public long scheduleTime {
            get {
                return this.scheduleTimeField;
            }
            set {
                this.scheduleTimeField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string customNum {
            get {
                return this.customNumField;
            }
            set {
                this.customNumField = value;
            }
        }
        
        /// <remarks/>
        public long deadline {
            get {
                return this.deadlineField;
            }
            set {
                this.deadlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class AccountInfo {
        
        private string accountField;
        
        private string nameField;
        
        private string identifyField;
        
        private string[] bizNamesField;
        
        private string userbriefField;
        
        private decimal balanceField;
        
        private string reserveField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Identify {
            get {
                return this.identifyField;
            }
            set {
                this.identifyField = value;
            }
        }
        
        /// <remarks/>
        public string[] BizNames {
            get {
                return this.bizNamesField;
            }
            set {
                this.bizNamesField = value;
            }
        }
        
        /// <remarks/>
        public string Userbrief {
            get {
                return this.userbriefField;
            }
            set {
                this.userbriefField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class BindChannel {
        
        private string channelNumField;
        
        private string carrierField;
        
        private string sendTypeField;
        
        /// <remarks/>
        public string ChannelNum {
            get {
                return this.channelNumField;
            }
            set {
                this.channelNumField = value;
            }
        }
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.139130.net")]
    public partial class BusinessType {
        
        private int idField;
        
        private string nameField;
        
        private int priorityField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private bool extendFlagField;
        
        private int stateField;
        
        private BindChannel[] bindChsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool ExtendFlag {
            get {
                return this.extendFlagField;
            }
            set {
                this.extendFlagField = value;
            }
        }
        
        /// <remarks/>
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public BindChannel[] bindChs {
            get {
                return this.bindChsField;
            }
            set {
                this.bindChsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMOMessageCompletedEventHandler(object sender, GetMOMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMOMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMOMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MOMsg[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MOMsg[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMOMessageForNeedConfirmCompletedEventHandler(object sender, GetMOMessageForNeedConfirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMOMessageForNeedConfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMOMessageForNeedConfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MOMsg[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MOMsg[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetBusinessTypeCompletedEventHandler(object sender, GetBusinessTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusinessTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBusinessTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BusinessType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BusinessType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAccountInfoCompletedEventHandler(object sender, GetAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ModifyPasswordCompletedEventHandler(object sender, ModifyPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostCompletedEventHandler(object sender, PostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GsmsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GsmsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostSingleCompletedEventHandler(object sender, PostSingleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostSingleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostSingleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostMassCompletedEventHandler(object sender, PostMassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostMassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostMassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PostGroupCompletedEventHandler(object sender, PostGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetResponseCompletedEventHandler(object sender, GetResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MTResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MTResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetReportCompletedEventHandler(object sender, GetReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MTReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MTReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetReportForNeedConfirmCompletedEventHandler(object sender, GetReportForNeedConfirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportForNeedConfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportForNeedConfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MTReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MTReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConfirmReportCompletedEventHandler(object sender, ConfirmReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConfirmMOMessageCompletedEventHandler(object sender, ConfirmMOMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmMOMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmMOMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindResponseCompletedEventHandler(object sender, FindResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MTResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MTResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindReportCompletedEventHandler(object sender, FindReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MTReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MTReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetMediasCompletedEventHandler(object sender, SetMediasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetMediasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetMediasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MediaItems[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MediaItems[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591